org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.87

## Mod Properties
mod_id=visuality
mod_name=visuality-forge
mod_license=MIT
mod_version=3.0.0
mod_group_id=plus.dragons.visuality
mod_authors=LimonBlaze
mod_description=Little visual improvements by adding a bunch of new particles.
