org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# you can also find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.07.20
# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.8
minecraft_version_range=[1.21.6, 1.22)
neo_version=21.8.36
neo_version_range=[21.8.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=visuality
mod_name=visuality-forge
mod_license=MIT
mod_version=3.0.0
mod_group_id=plus.dragons.visuality
mod_authors=LimonBlaze
mod_description=Little visual improvements by adding a bunch of new particles.
